//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelOrders.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ItemService
    {
        public int IDItem { get; set; }
        public Nullable<int> ServiceID { get; set; }
        [Required]
        public string Details { get; set; }
    
        public virtual Service Service { get; set; }
    }
}
